# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_interface.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(906, 730)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../.designer/backup/images/Leadership-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(170, 170, 127);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.appStackedPages = QtWidgets.QStackedWidget(self.centralwidget)
        self.appStackedPages.setObjectName("appStackedPages")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.page)
        self.label_5.setStyleSheet("font: 75 36pt \"Century Schoolbook L\";\n"
"color: rgb(85, 85, 127);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(207, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(50)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.addBtn = QtWidgets.QPushButton(self.page)
        self.addBtn.setMinimumSize(QtCore.QSize(120, 60))
        self.addBtn.setMaximumSize(QtCore.QSize(120, 60))
        self.addBtn.setStyleSheet("border:1px solid;\n"
"background-color: rgb(255, 170, 0);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 18pt \"Umpush\";\n"
"border-radius:10px;\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/747968.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addBtn.setIcon(icon1)
        self.addBtn.setObjectName("addBtn")
        self.verticalLayout_4.addWidget(self.addBtn)
        self.checkBtn = QtWidgets.QPushButton(self.page)
        self.checkBtn.setMinimumSize(QtCore.QSize(120, 60))
        self.checkBtn.setMaximumSize(QtCore.QSize(120, 60))
        self.checkBtn.setStyleSheet("border:1px solid ;\n"
"color: rgb(0, 0, 0);\n"
"font: 75 18pt \"Ubuntu\";\n"
"background-color: rgb(255, 170, 0);\n"
"border-radius:10px;\n"
"border-color: rgb(0, 0, 0);\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/214353.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBtn.setIcon(icon2)
        self.checkBtn.setObjectName("checkBtn")
        self.verticalLayout_4.addWidget(self.checkBtn)
        self.trainBtn = QtWidgets.QPushButton(self.page)
        self.trainBtn.setMinimumSize(QtCore.QSize(120, 60))
        self.trainBtn.setMaximumSize(QtCore.QSize(120, 60))
        self.trainBtn.setStyleSheet("border:1px solid;\n"
"font: 75 18pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);\n"
"border-radius:10px;\n"
"background-color: rgb(255, 170, 0);")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/189792.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.trainBtn.setIcon(icon3)
        self.trainBtn.setObjectName("trainBtn")
        self.verticalLayout_4.addWidget(self.trainBtn)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        spacerItem2 = QtWidgets.QSpacerItem(207, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 168, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.appStackedPages.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox = QtWidgets.QGroupBox(self.page_2)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.imageViewerLbl = QtWidgets.QLabel(self.groupBox)
        self.imageViewerLbl.setMinimumSize(QtCore.QSize(400, 350))
        self.imageViewerLbl.setMaximumSize(QtCore.QSize(400, 350))
        self.imageViewerLbl.setStyleSheet("border:2px solid rgb(0, 170, 255);\n"
"border-radius:10px;\n"
"")
        self.imageViewerLbl.setText("")
        self.imageViewerLbl.setPixmap(QtGui.QPixmap("images/133967.svg"))
        self.imageViewerLbl.setScaledContents(True)
        self.imageViewerLbl.setObjectName("imageViewerLbl")
        self.horizontalLayout_7.addWidget(self.imageViewerLbl)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setStyleSheet("color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.nameLin = QtWidgets.QLineEdit(self.groupBox)
        self.nameLin.setObjectName("nameLin")
        self.gridLayout_2.addWidget(self.nameLin, 0, 1, 1, 1)
        self.namevalid = QtWidgets.QLabel(self.groupBox)
        self.namevalid.setObjectName("namevalid")
        self.gridLayout_2.addWidget(self.namevalid, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.lnidLin = QtWidgets.QLineEdit(self.groupBox)
        self.lnidLin.setMaxLength(14)
        self.lnidLin.setObjectName("lnidLin")
        self.gridLayout_4.addWidget(self.lnidLin, 0, 1, 1, 1)
        self.nidvalid = QtWidgets.QLabel(self.groupBox)
        self.nidvalid.setObjectName("nidvalid")
        self.gridLayout_4.addWidget(self.nidvalid, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.addressLin = QtWidgets.QLineEdit(self.groupBox)
        self.addressLin.setObjectName("addressLin")
        self.horizontalLayout_5.addWidget(self.addressLin)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.maleCheckOpt = QtWidgets.QRadioButton(self.groupBox)
        self.maleCheckOpt.setStyleSheet("color: rgb(0, 0, 0);")
        self.maleCheckOpt.setChecked(True)
        self.maleCheckOpt.setObjectName("maleCheckOpt")
        self.horizontalLayout_4.addWidget(self.maleCheckOpt)
        self.femaleCheckOpt = QtWidgets.QRadioButton(self.groupBox)
        self.femaleCheckOpt.setStyleSheet("color: rgb(0, 0, 0);")
        self.femaleCheckOpt.setObjectName("femaleCheckOpt")
        self.horizontalLayout_4.addWidget(self.femaleCheckOpt)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.addTrainingImagesBtn = QtWidgets.QPushButton(self.groupBox)
        self.addTrainingImagesBtn.setMinimumSize(QtCore.QSize(80, 0))
        self.addTrainingImagesBtn.setObjectName("addTrainingImagesBtn")
        self.horizontalLayout_2.addWidget(self.addTrainingImagesBtn)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem8 = QtWidgets.QSpacerItem(20, 118, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.BackButton = QtWidgets.QPushButton(self.groupBox)
        self.BackButton.setMinimumSize(QtCore.QSize(100, 26))
        self.BackButton.setObjectName("BackButton")
        self.horizontalLayout_3.addWidget(self.BackButton)
        self.saveUserBtn = QtWidgets.QPushButton(self.groupBox)
        self.saveUserBtn.setMinimumSize(QtCore.QSize(100, 0))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../../../.designer/backup/images/unnamed.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveUserBtn.setIcon(icon4)
        self.saveUserBtn.setObjectName("saveUserBtn")
        self.horizontalLayout_3.addWidget(self.saveUserBtn)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem10)
        self.horizontalLayout_3.setStretch(3, 4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.appStackedPages.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.camera_viewer = QtWidgets.QLabel(self.page_3)
        self.camera_viewer.setStyleSheet("border:2px solid rgb(0, 170, 255);\n"
"border-radius:10px;")
        self.camera_viewer.setText("")
        self.camera_viewer.setScaledContents(True)
        self.camera_viewer.setObjectName("camera_viewer")
        self.gridLayout_3.addWidget(self.camera_viewer, 0, 0, 1, 1)
        self.appStackedPages.addWidget(self.page_3)
        self.verticalLayout_3.addWidget(self.appStackedPages)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 906, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_2.setObjectName("toolBar_2")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.toolBar_3 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_3.setObjectName("toolBar_3")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_3)
        self.toolBar_4 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_4.setObjectName("toolBar_4")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_4)
        self.toolBar_5 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_5.setObjectName("toolBar_5")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_5)
        self.toolBar_6 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_6.setObjectName("toolBar_6")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_6)
        self.toolBar_7 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_7.setObjectName("toolBar_7")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_7)
        self.toolBar_8 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_8.setObjectName("toolBar_8")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_8)
        self.toolBar_9 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_9.setObjectName("toolBar_9")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_9)
        self.toolBar_10 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_10.setObjectName("toolBar_10")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_10)
        self.toolBar_11 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_11.setObjectName("toolBar_11")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_11)

        self.retranslateUi(MainWindow)
        self.appStackedPages.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Face Recognition"))
        self.label_5.setText(_translate("MainWindow", "Intruder Detection System"))
        self.addBtn.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">Add New User</p></body></html>"))
        self.addBtn.setText(_translate("MainWindow", "Add "))
        self.checkBtn.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">Check User in DataBase</p></body></html>"))
        self.checkBtn.setText(_translate("MainWindow", "Check"))
        self.trainBtn.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">Refresh Data</p></body></html>"))
        self.trainBtn.setText(_translate("MainWindow", "Train"))
        self.groupBox.setTitle(_translate("MainWindow", "add new user"))
        self.label.setText(_translate("MainWindow", "name"))
        self.namevalid.setText(_translate("MainWindow", "vaild char"))
        self.label_2.setText(_translate("MainWindow", "NID"))
        self.nidvalid.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "address"))
        self.label_4.setText(_translate("MainWindow", "gender"))
        self.maleCheckOpt.setText(_translate("MainWindow", "male"))
        self.femaleCheckOpt.setText(_translate("MainWindow", "female"))
        self.addTrainingImagesBtn.setText(_translate("MainWindow", "add phots"))
        self.BackButton.setText(_translate("MainWindow", "Back"))
        self.saveUserBtn.setText(_translate("MainWindow", "save"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2"))
        self.toolBar_3.setWindowTitle(_translate("MainWindow", "toolBar_3"))
        self.toolBar_4.setWindowTitle(_translate("MainWindow", "toolBar_4"))
        self.toolBar_5.setWindowTitle(_translate("MainWindow", "toolBar_5"))
        self.toolBar_6.setWindowTitle(_translate("MainWindow", "toolBar_6"))
        self.toolBar_7.setWindowTitle(_translate("MainWindow", "toolBar_7"))
        self.toolBar_8.setWindowTitle(_translate("MainWindow", "toolBar_8"))
        self.toolBar_9.setWindowTitle(_translate("MainWindow", "toolBar_9"))
        self.toolBar_10.setWindowTitle(_translate("MainWindow", "toolBar_10"))
        self.toolBar_11.setWindowTitle(_translate("MainWindow", "toolBar_11"))

